// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN4p1UHXwuuUA7Ym8_KtxYUt7Xx1ckZZU',
    appId: '1:436096649025:web:2c0871ce218b577f65c3c0',
    messagingSenderId: '436096649025',
    projectId: 'flutter-toolshare',
    authDomain: 'flutter-toolshare.firebaseapp.com',
    storageBucket: 'flutter-toolshare.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAap51bWOSzVBj-t808awDZhznb_D-iRR4',
    appId: '1:436096649025:android:a09f76eb7dc90f0c65c3c0',
    messagingSenderId: '436096649025',
    projectId: 'flutter-toolshare',
    storageBucket: 'flutter-toolshare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAteP-KmUCcUmpm2tGPs7aq-3UB6h0GAec',
    appId: '1:436096649025:ios:859ed31da06a77b465c3c0',
    messagingSenderId: '436096649025',
    projectId: 'flutter-toolshare',
    storageBucket: 'flutter-toolshare.firebasestorage.app',
    iosBundleId: 'com.example.toolShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAteP-KmUCcUmpm2tGPs7aq-3UB6h0GAec',
    appId: '1:436096649025:ios:859ed31da06a77b465c3c0',
    messagingSenderId: '436096649025',
    projectId: 'flutter-toolshare',
    storageBucket: 'flutter-toolshare.firebasestorage.app',
    iosBundleId: 'com.example.toolShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN4p1UHXwuuUA7Ym8_KtxYUt7Xx1ckZZU',
    appId: '1:436096649025:web:e224e0a522ec3e1a65c3c0',
    messagingSenderId: '436096649025',
    projectId: 'flutter-toolshare',
    authDomain: 'flutter-toolshare.firebaseapp.com',
    storageBucket: 'flutter-toolshare.firebasestorage.app',
  );
}
